version: "3.3"

services:
  
  sql-server-express:
    env_file: .env
    # network_mode: host
    restart: always

    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu

    volumes:
      - ./volumes/mssql:/var/opt/mssql

    ports:
      - "${SQL_SERVER_PUERTO_EXPUESTO}:${SQL_SERVER_PUERTO_INTERNO}"
