version: "3.7"

services:

  db2:
    image: ibmcom/db2:11.5.0.0
    restart: always
    privileged: true
    
    env_file: 
      - ./docker-env/db2.env
    
    volumes:
      - ./volumes/db2:/database
    
    ports:
      - "50000:50000"