version: "3.3"

services:
    redis:
        image: redis
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes

        volumes:
            - ./volumes/data:/data
            - ./volumes/config/:/usr/local/etc/redis/

        ports:
            - "6379:6379"
