version: "3.7"

services:
  sonar-service:
    image: sonarqube
    restart: always

    volumes:
      - ./volumes/sonarqube/conf:/opt/sonarqube/conf
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/logs:/opt/sonarqube/logs

    ports:
      - ${EXTERNAL_PORT:-9000}:9000

networks:
  default:
    external:
      name: phantom-network
