version: "3.7"

services:

    redis:
        image: redis:5.0.7
        restart: always
        
        env_file: 
            - ./docker-env/redis.env

        volumes:
            - ./volumes/redis/data:/data

        ports:
            - "6379:6379"

        command: redis-server --appendonly yes