version: "3.3"

services:
    redis:
        image: redis
        env_file: .env
        restart: always

        volumes:
            - ./volumes/data:/data
            - ./volumes/config/:/usr/local/etc/redis/

        ports:
            - "${REDIS_PUERTO_EXPUESTO}:6379"

        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes