version: "3.7"

services:

    neo4j:
        image: neo4j:4.0.3
        restart: always
        
        env_file: 
            - ./docker-env/neo4j.env

        volumes:
            - ~/volumes/neo4j/data:/data

        ports:
            - 7474:7474
            - 7687:7687