version: "3.7"

services:

    greenplum:
        image: datagrip/greenplum:latest
        restart: always
        env_file: 
            - ./docker-env/greenplum.env
        volumes: 
            - greenplum:/gpdata:rw
        ports:
            - 5432:5432

networks:
    default:
        external:
            name: docker-net
    
volumes:
    greenplum:
        external: false
              