version: "3.7"

services:

    jenkins:
        image: jenkins/jenkins:lts
        restart: always
        user: root
        env_file: 
            - ./docker-env/jenkins.env

        volumes:
            - ./volumes/jenkins:/var/jenkins_home:rw

        ports:
            - "10000:8080"
            - "50000:50000"
