version: "3.7"

services:

  postgres:
    image: postgres
    restart: always
    
    env_file: 
      - ./docker-env/postgres.env
    
    volumes:
      - ./volumes/postgres/postgres-data:/var/lib/postgresql/data
      - ./volumes/postgres/sql/:/volumes/sql/
      
    ports:
      - "5432:5432"
